# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccatos < Formula
  desc "cat on steroids."
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/batmac/ccat/releases/download/v1.0.0/ccat-1.0.0-darwin-arm64.tar.gz"
      sha256 "73f2f9b074cd99721ce6a1a5f2b635e6124c9307466461f643e90341e98cacb9"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v1.0.0/ccat-1.0.0-darwin-amd64.tar.gz"
      sha256 "575f7d80b0d7b58c0142c33a78e1b87fb2d44aa4ff4fc204a68905778a406141"

      def install
        bin.install "ccat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v1.0.0/ccat-1.0.0-linux-armv6.tar.gz"
      sha256 "28a052615e408be60b03280b1a37456532c111bc4e6f499685024fc847f1fa4c"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v1.0.0/ccat-1.0.0-linux-arm64.tar.gz"
      sha256 "e1be24d4201db4a2dabb71e266cbe8bd8ed5d85fedc6031d8eae6031c801f68c"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v1.0.0/ccat-1.0.0-linux-amd64.tar.gz"
      sha256 "8f3bca8ad1cc861df795a10392c2160cd2a11b7f74f268cb7e321ffcc10834f5"

      def install
        bin.install "ccat"
      end
    end
  end

  conflicts_with "ccat"

  test do
    system "#{bin}/ccat --version"
  end
end
