# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccatos < Formula
  desc "cat on steroids."
  homepage ""
  version "1.13.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/batmac/ccat/releases/download/v1.13.3/ccat-1.13.3-darwin-arm64.tar.gz"
      sha256 "5112ba1cd7c7cadf7618ed0b22c1589cefd8d365e0c9e5933ab88df151cf68ba"

      def install
        bin.install "ccat"
        (bash_completion/"ccatos").write `#{bin}/ccat --completion bash`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v1.13.3/ccat-1.13.3-darwin-amd64.tar.gz"
      sha256 "8bdd56b20abc855e1ba284d418a7b4211b31b59a0f4626ebed2775bdbf0a78d8"

      def install
        bin.install "ccat"
        (bash_completion/"ccatos").write `#{bin}/ccat --completion bash`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v1.13.3/ccat-1.13.3-linux-armv6.tar.gz"
      sha256 "7e85a0aba4ab853947f5516978cbd53bb687e58af88846c80478f1d67aa79426"

      def install
        bin.install "ccat"
        (bash_completion/"ccatos").write `#{bin}/ccat --completion bash`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v1.13.3/ccat-1.13.3-linux-arm64.tar.gz"
      sha256 "82c6a785e1dc07e98efd9b905b3c23698dac68dcb5595578919606af12fc4348"

      def install
        bin.install "ccat"
        (bash_completion/"ccatos").write `#{bin}/ccat --completion bash`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v1.13.3/ccat-1.13.3-linux-amd64.tar.gz"
      sha256 "a96b771c476fc5d680a8d2553c5d59f9bc94e050281e8525f5ed46dbe3fc9aaf"

      def install
        bin.install "ccat"
        (bash_completion/"ccatos").write `#{bin}/ccat --completion bash`
      end
    end
  end

  conflicts_with "ccat"
  conflicts_with "ccrypt"

  test do
    system "#{bin}/ccat --version"
  end
end
