# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccatos < Formula
  desc "cat on steroids."
  homepage ""
  version "0.9.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/batmac/ccat/releases/download/v0.9.23/ccat-0.9.23-darwin-arm64.tar.gz"
      sha256 "3ded5f5a4b0872e6d38640da8329cfaa674b0d40fd8c15dc1bd843ecf1b17409"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v0.9.23/ccat-0.9.23-darwin-amd64.tar.gz"
      sha256 "b8fd80d0b025973990548f28fb1de64e72aa4e99de75286595358a7d649a774a"

      def install
        bin.install "ccat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v0.9.23/ccat-0.9.23-linux-armv6.tar.gz"
      sha256 "eb0069d3dee0e7b30a62d01d2e39fd2cd5b0047a4ebefb76a1ae39922f983366"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v0.9.23/ccat-0.9.23-linux-arm64.tar.gz"
      sha256 "8a1d4448be03435240e00d3485eb1b5a0eada71dad9e12a89d614bf66d5a0724"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v0.9.23/ccat-0.9.23-linux-amd64.tar.gz"
      sha256 "0dff706b066a48d6266a29127a495da582f21b7fb1b971fb1a0a592821d808af"

      def install
        bin.install "ccat"
      end
    end
  end

  conflicts_with "ccat"

  test do
    system "#{bin}/ccat --version"
  end
end
